import { FraudAlert, FraudAlertSeverity } from '../entities/fraud-alert.entity';
import { Transaction } from '../entities/transaction.entity';

/**
 * Configuration for the fraud detection rules.
 * Values come from environment variables via the application layer.
 */
export interface FraudConfig {
  /** The monetary threshold above which a transaction is flagged (decimal). Default: 10,000. */
  amountThreshold: number;

  /** The time window in minutes for velocity checks. Default: 5. */
  velocityWindowMinutes: number;

  /** Max transactions allowed in the velocity window. Default: 10. */
  velocityMaxTransactions: number;
}

/**
 * Result of a fraud analysis. Contains zero or more alerts.
 */
export class FraudAnalysisResult {
  constructor(
    /** The alerts generated by the analysis. Empty array if no fraud detected. */
    public readonly alerts: FraudAlert[],
  ) {}

  /**
   * Returns true if the analysis generated any alerts.
   */
  hasAlerts(): boolean {
    return this.alerts.length > 0;
  }

  /**
   * Returns the highest severity across all alerts, or null if no alerts.
   */
  highestSeverity(): FraudAlertSeverity | null {
    if (this.alerts.length === 0) return null;

    const severityOrder: Record<FraudAlertSeverity, number> = {
      LOW: 1,
      MEDIUM: 2,
      HIGH: 3,
      CRITICAL: 4,
    };

    return this.alerts.reduce<FraudAlertSeverity>((highest, alert) => {
      return severityOrder[alert.severity] > severityOrder[highest]
        ? alert.severity
        : highest;
    }, this.alerts[0].severity);
  }
}

/**
 * Pure domain service for fraud detection.
 *
 * Analyzes a transaction against configurable fraud rules:
 * 1. Amount threshold: flags transactions exceeding a configured amount.
 * 2. Velocity check: flags users making too many transactions in a time window.
 *
 * This service has ZERO framework dependencies. It receives its configuration
 * through the constructor and operates on domain entities directly.
 *
 * The application layer is responsible for:
 * - Providing the FraudConfig (from environment variables)
 * - Fetching recent transactions from the repository
 * - Persisting any generated FraudAlert entities
 * - Publishing FraudAlertCreatedEvent domain events
 *
 * @example
 * const service = new FraudDetectionService(config);
 * const result = service.analyze(transaction, recentTransactions);
 * if (result.hasAlerts()) {
 *   for (const alert of result.alerts) {
 *     await alertRepository.save(alert);
 *   }
 * }
 */
export class FraudDetectionService {
  constructor(private readonly config: FraudConfig) {}

  /**
   * Analyzes a transaction for potential fraud patterns.
   *
   * Checks both amount threshold and velocity rules. Each rule
   * independently determines whether to generate an alert and at
   * what severity level.
   *
   * @param transaction - The transaction to analyze
   * @param recentTransactions - Recent transactions for the same user
   *                             (used for velocity calculation)
   * @returns FraudAnalysisResult containing zero or more FraudAlert entities
   */
  analyze(
    transaction: Transaction,
    recentTransactions: Transaction[],
  ): FraudAnalysisResult {
    const alerts: FraudAlert[] = [];

    // Rule 1: Amount threshold check
    const amountAlert = this.checkAmountThreshold(transaction);
    if (amountAlert !== null) {
      alerts.push(amountAlert);
    }

    // Rule 2: Velocity check
    const velocityAlert = this.checkVelocity(transaction, recentTransactions);
    if (velocityAlert !== null) {
      alerts.push(velocityAlert);
    }

    return new FraudAnalysisResult(alerts);
  }

  /**
   * Checks if the transaction amount exceeds the configured threshold.
   *
   * Severity tiers for HIGH_AMOUNT alerts:
   *   - LOW:    amount > threshold AND amount < 2x threshold
   *   - MEDIUM: amount >= 2x threshold AND amount < 5x threshold
   *   - HIGH:   amount >= 5x threshold
   *
   * @param transaction - The transaction to check
   * @returns A FraudAlert if the threshold is exceeded, null otherwise
   */
  private checkAmountThreshold(transaction: Transaction): FraudAlert | null {
    const amount = transaction.amount.value;
    const threshold = this.config.amountThreshold;

    if (amount <= threshold) {
      return null;
    }

    const severity = FraudAlert.calculateAmountSeverity(amount, threshold);

    return FraudAlert.create({
      transactionId: transaction.id,
      userId: transaction.userId,
      alertType: 'HIGH_AMOUNT',
      severity,
      details: {
        amount,
        threshold,
        ratio: Math.round((amount / threshold) * 100) / 100,
      },
    });
  }

  /**
   * Checks if the user's transaction velocity exceeds the configured limit.
   *
   * Counts the number of recent transactions within the configured time window
   * and compares against the maximum. The current transaction being analyzed
   * is included in the count (count = recentTransactions + 1).
   *
   * Severity tiers for VELOCITY alerts:
   *   - MEDIUM:   count > max
   *   - HIGH:     count > 2x max
   *   - CRITICAL: count > 5x max
   *
   * @param transaction - The current transaction being analyzed
   * @param recentTransactions - Transactions for the same user in the time window
   * @returns A FraudAlert if velocity is exceeded, null otherwise
   */
  private checkVelocity(
    transaction: Transaction,
    recentTransactions: Transaction[],
  ): FraudAlert | null {
    const windowMs = this.config.velocityWindowMinutes * 60 * 1000;
    const windowStart = new Date(transaction.createdAt.getTime() - windowMs);

    const transactionsInWindow = recentTransactions.filter(
      (t) => t.createdAt.getTime() >= windowStart.getTime(),
    );

    // Include the current transaction in the count
    const totalCount = transactionsInWindow.length + 1;
    const maxTransactions = this.config.velocityMaxTransactions;

    if (totalCount <= maxTransactions) {
      return null;
    }

    const severity = FraudAlert.calculateVelocitySeverity(totalCount, maxTransactions);

    return FraudAlert.create({
      transactionId: transaction.id,
      userId: transaction.userId,
      alertType: 'VELOCITY',
      severity,
      details: {
        transactionCount: totalCount,
        maxTransactions,
        windowMinutes: this.config.velocityWindowMinutes,
        ratio: Math.round((totalCount / maxTransactions) * 100) / 100,
      },
    });
  }
}
